### PR TITLE
remove index from string so that the contains operator works

### PR DESCRIPTION
**Pull request by drewdeal**
had to assign variable and truncate "index" off so that playbooks show subnavigation highlight based on path.

### CODE REVIEW

**Review by bdfinst — COMMENTED** [review]
How do I test this?

**Comment by drewdeal** [comment]
In nested playbook, subcat in menu still highlighted.

I will put up another commit though to fix the bug. Don't merge

**Comment by drewdeal** [comment]
Ok Bryan. It is solid now.
easy testing:
http://127.0.0.1:4000/docs/playbooks/lean/index.html ---> Lean highlighted
http://127.0.0.1:4000/docs/playbooks/lean/wm-vsm.html ---> Lean highlighted
Overview not highlighted unless http://127.0.0.1:4000/docs/playbooks/index.html 
:-)

**Review by bdfinst — APPROVED** [review]
LGTM

**Pull request merged**
